global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "application-server-node-exporter"
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: "application-server-push-gateway"
    static_configs:
      - targets: ["localhost:9091"]
rule_files:
  - "/usr/local/etc/rule/alerts.yml"
  - "/usr/local/etc/rule/recording_rule.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093
