groups:
  - name: node_cpu_recording_rules
    rules:
      - record: cpu:node_cpu_usage:avg1m # <level>:<metric_name>:<operation> <operation> is optional . eg avg by(cpu)( rate    (node_cpu_seconds_total[1m]))
        expr: avg by(cpu) (rate(node_cpu_seconds_total[1m]))
        labels:
          exporter_type: node_exporter
